# Generated by Django 5.0.1 on 2024-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_url_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('REST', 'Real Estates'), ('BTY', 'Beauty'), ('FSHN', 'Fashion'), ('G&DIY', 'Garden & DYI'), ('AUTO', 'Motorization'), ('ELECT', 'Electronics'), ('ARTS', 'Arts'), ('ENTER', 'Entertainment'), ('CHLD', 'Child')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('UP', 'Used - Poor'), ('UG', 'Used - Good'), ('DMG', 'Damaged'), ('LN', 'Like New'), ('UF', 'Used - Fair')], max_length=3),
        ),
    ]
