# Generated by Django 5.0.1 on 2024-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_image_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ARTS', 'Arts'), ('G&DIY', 'Garden & DYI'), ('REST', 'Real Estates'), ('CHLD', 'Child'), ('ENTER', 'Entertainment'), ('FSHN', 'Fashion'), ('ELECT', 'Electronics'), ('AUTO', 'Motorization'), ('BTY', 'Beauty')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('UG', 'Used - Good'), ('DMG', 'Damaged'), ('LN', 'Like New'), ('UF', 'Used - Fair'), ('UP', 'Used - Poor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_directory_path'),
        ),
    ]
