# Generated by Django 5.0.1 on 2024-02-18 19:51

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category_alter_listing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CHLD', 'Child'), ('REST', 'Real Estates'), ('ELECT', 'Electronics'), ('FSHN', 'Fashion'), ('BTY', 'Beauty'), ('G&DIY', 'Garden & DYI'), ('AUTO', 'Motorization'), ('ENTER', 'Entertainment'), ('ARTS', 'Arts')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UG', 'Used - Good'), ('UP', 'Used - Poor'), ('UF', 'Used - Fair'), ('LN', 'Like New'), ('DMG', 'Damaged'), ('N', 'New')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to=auctions.models.user_directory_path),
        ),
    ]
