# Generated by Django 5.0.1 on 2024-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_category_alter_listing_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='url',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('BTY', 'Beauty'), ('CHLD', 'Child'), ('ELECT', 'Electronics'), ('FSHN', 'Fashion'), ('ARTS', 'Arts'), ('REST', 'Real Estates'), ('G&DIY', 'Garden & DYI'), ('ENTER', 'Entertainment'), ('AUTO', 'Motorization')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UG', 'Used - Good'), ('UP', 'Used - Poor'), ('DMG', 'Damaged'), ('N', 'New'), ('UF', 'Used - Fair'), ('LN', 'Like New')], max_length=3),
        ),
    ]
