# Generated by Django 5.0.1 on 2024-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_url_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('BTY', 'Beauty'), ('G&DIY', 'Garden & DYI'), ('AUTO', 'Motorization'), ('ARTS', 'Arts'), ('CHLD', 'Child'), ('ELECT', 'Electronics'), ('REST', 'Real Estates'), ('FSHN', 'Fashion'), ('ENTER', 'Entertainment')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('LN', 'Like New'), ('UF', 'Used - Fair'), ('UG', 'Used - Good'), ('UP', 'Used - Poor'), ('DMG', 'Damaged')], max_length=3),
        ),
    ]
