# Generated by Django 5.0.2 on 2024-03-04 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_wishlist_watchlist_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AUTO', 'Motorization'), ('BTY', 'Beauty'), ('ARTS', 'Arts'), ('G&DIY', 'Garden & DYI'), ('ELECT', 'Electronics'), ('ENTER', 'Entertainment'), ('CHLD', 'Child'), ('REST', 'Real Estates'), ('FSHN', 'Fashion')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('LN', 'Like New'), ('UG', 'Used - Good'), ('DMG', 'Damaged'), ('UP', 'Used - Poor'), ('UF', 'Used - Fair')], max_length=3),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(related_name='listings_on_watchlist', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
