# Generated by Django 5.0.2 on 2024-03-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_category_alter_listing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('G&DIY', 'Garden & DYI'), ('AUTO', 'Motorization'), ('BTY', 'Beauty'), ('FSHN', 'Fashion'), ('REST', 'Real Estates'), ('ENTER', 'Entertainment'), ('ELECT', 'Electronics'), ('CHLD', 'Child'), ('ARTS', 'Arts')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('LN', 'Like New'), ('DMG', 'Damaged'), ('N', 'New'), ('UG', 'Used - Good'), ('UF', 'Used - Fair'), ('UP', 'Used - Poor')], max_length=3),
        ),
    ]
