# Generated by Django 5.0.2 on 2024-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_category_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('G&DIY', 'Garden & DYI'), ('BTY', 'Beauty'), ('ARTS', 'Arts'), ('REST', 'Real Estates'), ('CHLD', 'Child'), ('ELECT', 'Electronics'), ('AUTO', 'Motorization'), ('ENTER', 'Entertainment'), ('FSHN', 'Fashion')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('DMG', 'Damaged'), ('UF', 'Used - Fair'), ('LN', 'Like New'), ('UG', 'Used - Good'), ('UP', 'Used - Poor')], max_length=3),
        ),
    ]
