# Generated by Django 5.0.2 on 2024-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FSHN', 'Fashion'), ('AUTO', 'Motorization'), ('ARTS', 'Arts'), ('BTY', 'Beauty'), ('ENTER', 'Entertainment'), ('REST', 'Real Estates'), ('ELECT', 'Electronics'), ('CHLD', 'Child'), ('G&DIY', 'Garden & DYI')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UG', 'Used - Good'), ('DMG', 'Damaged'), ('N', 'New'), ('UF', 'Used - Fair'), ('LN', 'Like New'), ('UP', 'Used - Poor')], max_length=3),
        ),
    ]
