# Generated by Django 5.0.2 on 2024-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_category_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FSHN', 'Fashion'), ('G&DIY', 'Garden & DYI'), ('AUTO', 'Motorization'), ('ELECT', 'Electronics'), ('ARTS', 'Arts'), ('BTY', 'Beauty'), ('REST', 'Real Estates'), ('CHLD', 'Child'), ('ENTER', 'Entertainment')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('LN', 'Like New'), ('N', 'New'), ('UF', 'Used - Fair'), ('DMG', 'Damaged'), ('UG', 'Used - Good'), ('UP', 'Used - Poor')], max_length=3),
        ),
    ]
