# Generated by Django 5.0.2 on 2024-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_category_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CHLD', 'Child'), ('ENTER', 'Entertainment'), ('ARTS', 'Arts'), ('FSHN', 'Fashion'), ('AUTO', 'Motorization'), ('G&DIY', 'Garden & DYI'), ('BTY', 'Beauty'), ('ELECT', 'Electronics'), ('REST', 'Real Estates')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UP', 'Used - Poor'), ('UF', 'Used - Fair'), ('UG', 'Used - Good'), ('LN', 'Like New'), ('DMG', 'Damaged'), ('N', 'New')], max_length=3),
        ),
    ]
