# Generated by Django 5.0.2 on 2024-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_category_alter_listing_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='seller',
            new_name='bidder',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AUTO', 'Motorization'), ('REST', 'Real Estates'), ('CHLD', 'Child'), ('BTY', 'Beauty'), ('ARTS', 'Arts'), ('FSHN', 'Fashion'), ('G&DIY', 'Garden & DYI'), ('ELECT', 'Electronics'), ('ENTER', 'Entertainment')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('LN', 'Like New'), ('N', 'New'), ('UP', 'Used - Poor'), ('UF', 'Used - Fair'), ('UG', 'Used - Good'), ('DMG', 'Damaged')], max_length=3),
        ),
    ]
