# Generated by Django 5.0.2 on 2024-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_seller_bid_bidder_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('BTY', 'Beauty'), ('REST', 'Real Estates'), ('CHLD', 'Child'), ('AUTO', 'Motorization'), ('G&DIY', 'Garden & DYI'), ('ELECT', 'Electronics'), ('ARTS', 'Arts'), ('FSHN', 'Fashion'), ('ENTER', 'Entertainment')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UF', 'Used - Fair'), ('DMG', 'Damaged'), ('UG', 'Used - Good'), ('LN', 'Like New'), ('UP', 'Used - Poor'), ('N', 'New')], max_length=3),
        ),
    ]
