# Generated by Django 5.0.2 on 2024-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_price_bid_bid_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ENTER', 'Entertainment'), ('G&DIY', 'Garden & DYI'), ('FSHN', 'Fashion'), ('BTY', 'Beauty'), ('AUTO', 'Motorization'), ('REST', 'Real Estates'), ('ELECT', 'Electronics'), ('ARTS', 'Arts'), ('CHLD', 'Child')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UG', 'Used - Good'), ('UF', 'Used - Fair'), ('N', 'New'), ('LN', 'Like New'), ('UP', 'Used - Poor'), ('DMG', 'Damaged')], max_length=3),
        ),
    ]
