# Generated by Django 5.0.2 on 2024-03-11 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_category_alter_listing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sold_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ENTER', 'Entertainment'), ('ELECT', 'Electronics'), ('CHLD', 'Child'), ('G&DIY', 'Garden & DYI'), ('AUTO', 'Motorization'), ('FSHN', 'Fashion'), ('BTY', 'Beauty'), ('REST', 'Real Estates'), ('ARTS', 'Arts')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UG', 'Used - Good'), ('LN', 'Like New'), ('DMG', 'Damaged'), ('UF', 'Used - Fair'), ('N', 'New'), ('UP', 'Used - Poor')], max_length=3),
        ),
    ]
