# Generated by Django 5.0.6 on 2024-08-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_comment_date_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CHLD', 'Child'), ('ENTER', 'Entertainment'), ('G&DIY', 'Garden & DYI'), ('ARTS', 'Arts'), ('FSHN', 'Fashion'), ('AUTO', 'Motorization'), ('REST', 'Real Estates'), ('BTY', 'Beauty'), ('ELECT', 'Electronics')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('UF', 'Used - Fair'), ('DMG', 'Damaged'), ('UP', 'Used - Poor'), ('UG', 'Used - Good'), ('LN', 'Like New'), ('N', 'New')], max_length=3),
        ),
    ]
